enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
[Sync]
apkmirror-dlurl = "https://apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
build-mode = "module"
patcher-args = "-e 'Spoof client' -Oclient-id=9r9AUm0maHurYsl4nfb1PA"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
excluded-patches = "'GmsCore support'"
